// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezfjzhcpfjnulgmsgvgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6Zmp6aGNwZmpudWxnbXNndmdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDAwODEsImV4cCI6MjA2MDgxNjA4MX0.bvdLoJ6hV9rFqj6hshjKijVshaoOe4Cy_z5tHE7efm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);